micronaut:
  application:
    name: casadocodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/cdc`}
    username: ${DB_USER:root}
    password: ${DB_USER:root}

jpa.default.properties.hibernate.hbm2ddl.auto: update
